a="Sandeep !!"
print(len(a))
print(a.upper())
print(a.lower())
print(a.title())
print(a.rstrip("!"))
print(a.replace("Sandeep","sanjeet"))
print(a.split(" "))
a="sandeep shah"
print(a.capitalize())
print(a.center(20))
print(a.count("s"))
print(a.endswith("h"))
print(a.endswith("a"))
print(a.startswith("s"))
print(a.find("e"))
print(a.index("e"))
print(a.isalnum())
print(a.isalpha())
print(a.islower())
print(a.isupper())
print(a.isspace())
print(a.isprintable())